name: Deploy

on:
  push:
    branches:
      - main
      - prod

jobs:
  test-lint:
    uses: ./.github/workflows/test-and-lint.yml
    name: Test and Lint
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH connect to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd ${{ vars.WORK_APP_DIR }}

            git pull origin main
            docker-compose pull
            docker-compose down
            echo "DB_NAME=${{ vars.DB_NAME }}" >> .env
            echo "DB_USER=${{ vars.DB_USER }}" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
            echo "DJANGO_ALLOWED_HOSTS=${{ secrets.VM_HOST }}" >> .env

            docker run -d --name dd-agent \
            -e DD_API_KEY=${{ secrets.DD_API_KEY }} \
            -e DD_SITE="datadoghq.eu" \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v /proc/:/host/proc/:ro \
            -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
            -v /var/lib/docker/containers:/var/lib/docker/containers:ro \
            gcr.io/datadoghq/agent:7

            docker-compose -f docker-compose-deploy.yml up -d --build